# Generated by Django 3.0.5 on 2020-05-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=122)),
                ('desc', models.CharField(max_length=5000)),
                ('submitter', models.CharField(max_length=122)),
            ],
        ),
    ]
