# Generated by Django 3.0.5 on 2020-05-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub',
            field=models.CharField(default='', max_length=2500),
        ),
    ]
